### ISSUE TITLE
Rust Nightly の devcontainer 環境構築

### ISSUE THREAD

**Issue by ytak-sagit** [ytak-sagit/hands-on-rust-browser-saba#1]
~~イチから Dockerfile 書いてカスタマイズ~~
- ~~参考になりそうなのは[このリポジトリ](https://github.com/xuhongxu96/vscode-container-rust-nightly/blob/master/.devcontainer/Dockerfile#L24)~~
- ~~`toolchain` のバージョンに `nightly` を指定する形~~
- ~~書籍に従い、`qemu-system` のインストール手順も追加~~

VSCode公式のRustイメージをベースとする Dockerfile を追加
- 書籍に従い、`qemu-system` のインストール手順も追加
- `rust-toolchain.toml` を追加し、プロジェクトルートに置いておく

```toml
[toolchain]
channel = "nightly-2024-01-01"
components = [ "rustfmt", "rust-src", "clippy" ]
targets = [ "x86_64-unknown-linux-gnu" ]
profile = "default"
```

参考
- [rust-toolchain.tomlを書こう | 東京科学大学デジタル創作同好会traP](https://trap.jp/post/2092/)

---

※当初は以下の方法を考えていたが、他に `apt install` する必要のあるものがあったため、上記で進めた

<details>

<summary>覚書: rust-toolchain.toml を使用する場合</summary>

- ベースとなる環境を構築後、`rust-toolchain.toml` で使用するバージョンを指定すれば良いのでは
  - ベースの環境構築は、別リポジトリでのハンズオン時にまとめた[開発環境構築](https://github.com/ytak-sagit/hands-on-rust-for-backend/wiki/%E9%96%8B%E7%99%BA%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89)に従って実施
  - `rust-toolchain.toml` は書籍の案内通りに設定
  - `rustup show` コマンド実施により、`nightly-2024-01-01` が表示されていればOK

</details>
